export const questions = [
  "Rewind to childhood: what's that one golden memory that makes you smile every time?",
  "Ever had that proud 'I did it!' moment? Spill the beans!",
  "Is there a magical corner of the world you've visited that still feels like a dream?",
  "Ever had your heart racing from fear? What happened?",
  "Your childhood partner-in-crime: who were they and what mischief did you get up to?",
  "Share that thrilling episode when adrenaline had the better of you.",
  "Life's tough lessons: what's that one episode you wouldn't want to relive, yet wouldn't trade for anything?",
  "Got a story that makes you chuckle every single time?",
  "Who's that one person whose influence on your life deserves its own biography?",
  "Those cozy family rituals: which one warms your heart the most?",
  "Remember the first story or book that grabbed your soul and whisked it away?",
  "Was there a moment that felt like a movie scene, making you see the world with fresh eyes?",
  "When were you so happy that you had tears rolling down your face?",
  "That nostalgic tune: which song is a time machine for you?",
  "Ever felt an otherworldly chill or sensed an unexplained presence?",
  "Decisions, decisions: which one felt like threading a needle while blindfolded?",
  "Ever been somewhere that felt like a personal sanctuary, where your soul could breathe?",
  "Share an instance where you threw the rulebook out the window and trusted your gut.",
  "Which journey felt less like travel and more like a transformative experience?",
  "Ever met someone and instantly thought, 'Ah, there's my tribe!'?",
  "Your childhood toy or game that wasn’t just a thing, but a world: which one was it?",
  "A mentor, a guiding star: who helped mold the version of you reading this?",
  "The whirlwind of first love: what's your story?",
  "A dream once close to your heart but now in the rearview mirror: what changed?",
  "Ever witnessed a mystery that you still can't quite wrap your head around?",
  "Recall that heroic moment you stood tall, against all odds.",
  "Bared your soul and felt utterly exposed: when was that?",
  "That place so breathtaking you couldn’t believe your eyes: where was it?",
  "Ever caught a whiff of a scent that transported you back in time?",
  "Was there a past obsession or hobby that consumed you day and night?",
  "Ever had fate wink at you? Describe that serendipitous moment.",
  "A dream that paid you multiple visits: what was it?",
  "The best gift that wasn't just an object but a memory: what was it?",
  "Share a gesture so kind it could melt the coldest of hearts.",
  "That wild instance where you felt like a fish out of water.",
  "The most vivid character you've encountered: who left an indelible mark on your memory?",
  "Expectations vs. Reality: Share a time when they were poles apart.",
  "A childhood nook or hideout you'd pay gold to revisit: where was it?",
  "Ever amazed yourself, thinking, 'Did I just do that?'",
  "Which birthday felt like a chapter right out of a novel?",
  "A movie or show that felt less like fiction and more like a personal letter to you: which one was it?",
  "If you could hop into a time machine, which historic moment would you be front row for?",
  "A cultural ritual that feels like a dance of the soul: what is it?"
];
